# Generated by Django 4.2.10 on 2024-09-20 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_posts',
            name='user',
            field=models.ManyToManyField(related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
