# Generated by Django 4.2.10 on 2024-09-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
