# Generated by Django 4.2.10 on 2024-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
    ]
